name: fake_products
description: "This is a Flutter app that displays a list of products, allowing users to search by name, view product details, add products to favorites, and access a screen dedicated to favorite items. The app includes search functionality with debounce, detailed product information display, and the ability to mark/unmark products as favorites."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_localization: ^0.3.0
  flutter_mobx: ^2.3.0
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  go_router: ^14.6.2
  mobx: ^2.5.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/empty_list.svg
   - assets/images/error.svg
  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 400
       - asset: assets/fonts/Poppins-Medium.ttf
         weight: 500
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-Bold.ttf
         weight: 700

# dart run build_runner build --delete-conflicting-outputs